-- AlterTable
ALTER TABLE "Categoria" ADD COLUMN     "imagen" TEXT,
ADD COLUMN     "popular" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Cliente" ALTER COLUMN "direccion" DROP NOT NULL,
ALTER COLUMN "telefono" DROP NOT NULL,
ALTER COLUMN "fechaRegistro" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Pedido" ALTER COLUMN "fecha" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Reporte" ALTER COLUMN "fecha" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Resena" ALTER COLUMN "calificacion" DROP NOT NULL,
ALTER COLUMN "comentario" DROP NOT NULL,
ALTER COLUMN "fecha" SET DEFAULT CURRENT_TIMESTAMP;
